# -*- coding: utf-8 -*-

# version: "2.1"
version: "3.7"

volumes:
  staticfeeds:

services:
  feedFacade:
    image: semweb/caphub_feedfacade:latest
    depends_on:
      - "rabbitmq"
      - "postgres"
    ports:
      - 8081:8080
    networks:
      default:
        aliases:
          - ffhost

  capAggregator:
    image: semweb/caphub_aggregator:latest
    depends_on:
      - "rabbitmq"
      - "es7"
      - "postgres"
    ports:
      - 8082:8080 
    volumes:
      - staticfeeds:/var/www/html/cap 
    networks:
      default:
        aliases:
          - cchost
