# -*- coding: utf-8 -*-

# version: "2.1"
version: "3.7"

volumes:
  cappgdata:
  capesdata:
  staticfeeds:

networks:
  fah:
    driver: overlay

services:
  #
  # docker exec -it pg psql -u postgres
  #
  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pa55w0rd
      POSTGRES_DB: postgres
    volumes:
      - cappgdata:/var/lib/postgresql/data
      - ./pginit:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      fah:
        aliases:
          - pghost
          - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "3"
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 20
      test:
        - "CMD-SHELL"
        - "pg_isready --dbname=postgres --host=localhost --username=postgres"


  # https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  # https://github.com/k-int/KBPlusG3/blob/dev-integration/SETUP-ES-DOCKER.txt
  # see https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  es7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx2g -Dfile.encoding=UTF-8"
      - discovery.type=single-node 
      - cluster.name=elasticsearch
      - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      - LC_ALL=en_US.UTF-8
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
    ports:
      - 9200:9200 
      - 9300:9300
    volumes:
      - capesdata:/usr/share/elasticsearch/data
    networks:
      fah:
        aliases:
          - eshost
          - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "3"
    healthcheck:
      timeout: 15s
      interval: 15s
      retries: 20
      test:
        - "CMD-SHELL"
        - "curl http://localhost:9200/_cluster/health | grep '.status.:.\\(green\\|yellow\\)'"


  rabbitmq:
    image: semweb/caphub_rabbit:latest
    hostname: rabbitmq
    # image: rabbitmq:management
    restart: always
    ports:
      - 15672:15672 
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=adm
      - RABBITMQ_DEFAULT_PASS=admpass 
      - RABBITMQ_NODENAME=cap@rabbitmq
    networks:
      fah:
        aliases:
          - rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "3"
    healthcheck:
      test: ["CMD", "bash", "-c", "rabbitmqctl list_exchanges | grep CAPExchange"]
      interval: 30s
      timeout: 20s
      retries: 20

  setup:
    image: semweb/caphub_setup:latest
    deploy:
      restart_policy:
        condition: "none"
    depends_on:
      - "rabbitmq"
      - "es7"
      - "postgres"
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "3"
    networks:
      fah:
        aliases:
          - setup

  # Useful info on wait here: https://dev.to/hugodias/wait-for-mongodb-to-start-on-docker-3h8b
  feedFacade:
    image: semweb/caphub_feedfacade:latest
    depends_on:
      - "rabbitmq"
      - "postgres"
    ports:
      - 8081:8080
    networks:
      fah:
        aliases:
          - ffhost
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "3"
    environment:
      WAIT_HOSTS: postgres:5432, rabbitmq:5672


  capAggregator:
    image: semweb/caphub_aggregator:latest
    depends_on:
      - "rabbitmq"
      - "es7"
      - "postgres"
    ports:
      - 8082:8080
    volumes:
      - staticfeeds:/var/www/html/cap 
    networks:
      fah:
        aliases:
          - cchost
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "3"
    environment:
      WAIT_HOSTS: postgres:5432, rabbitmq:5672, elasticsearch:9200

  nginx:
    image: semweb/caphub_nginx:latest
    depends_on:
      - "capAggregator"
      - "feedFacade"
    ports:
      - 80:80
    volumes:
      - staticfeeds:/var/www/html/cap
    networks:
      fah:
        aliases:
          - frontend
    environment:
      WAIT_HOSTS: cchost:8080, ffhost:8080
