# -*- coding: utf-8 -*-

# version: "2.1"
version: "3.7"

volumes:
  staticfeeds:

networks:
  fah:
    driver: overlay

services:
  feedFacade:
    image: semweb/caphub_feedfacade:latest
    depends_on:
      - "rabbitmq"
      - "postgres"
    ports:
      - 8081:8080
    networks:
      fah:
        aliases:
          - ffhost

  capAggregator:
    image: semweb/caphub_aggregator:latest
    depends_on:
      - "rabbitmq"
      - "es7"
      - "postgres"
    ports:
      - 8082:8080 
    volumes:
      - staticfeeds:/var/www/html/cap 
    networks:
      fah:
        aliases:
          - cchost

  nginx:
    image: semweb/caphub_nginx:latest
    ports:
      - 80:80
    volumes:
      - staticfeeds:/var/www/html/cap
    networks:
      fah:
        aliases:
          - frontend
   environment:
      WAIT_HOSTS: cchost:8080, ffhost:8080

